# TODO:
# - apply BKM
# - add configuration for default system applications
# - fix wornings
# - apply correct security
---
- hosts: noirinan
  become: yes
  become_user: root
  become_method: su
  vars:
    sudoers:
      - pietrushnic
  roles:
    - { role: avnes.ansible-role-slack, slack_tmp_dir: /tmp  }
    - role: debops.apt_preferences
      apt_preferences_group_list:
        - package: '*'
          suffix: '_stable'
          pin: 'release a=stable'
          priority: '1000'

        - package: '*'
          suffix: '_unstable'
          pin: 'release a=unstable'
          priority: '2'

      apt_preferences__list:
        - package: 'firefox'
          pin: 'release a=unstable'
          priority: '1001'

        - package: 'libfontconfig1'
          pin: 'release a=unstable'
          priority: '1001'

        - package: 'fontconfig-config'
          pin: 'release a=unstable'
          priority: '1001'

        - package: 'libnss3'
          pin: 'release a=unstable'
          priority: '1001'

  tasks:
    - name: Install sudo and zsh packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - sudo
        - zsh

    - name: Make sure we have a 'wheel' group
      group:
        name=wheel
        state=present

    - name: Allow wheel group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        shell: /bin/zsh
        append: yes
      with_items: "{{ sudoers }}"

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

    - apt_repository:
        repo: deb http://debian-archive.trafficmanager.net/debian/ unstable main
        state: present

    - apt_repository:
        repo: deb-src http://debian-archive.trafficmanager.net/debian/ unstable main
        state: present

    - apt_repository:
        repo: deb http://debian-archive.trafficmanager.net/debian/ stretch main contrib non-free
        state: present

    - apt_repository:
        repo: deb-src http://debian-archive.trafficmanager.net/debian/ stretch main contrib non-free
        state: present

    - apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410

    - apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
        state: present

    - name: Upgrade packages
      apt: upgrade=safe force=yes

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - build-essential
        - vim
        - git
        - minicom
        - telnet
        - ser2net
        - tmux
        - cscope
        - fonts-powerline
        - linux-headers-amd64
        - nvidia-driver
        - powerline
        - spotify-client
        - virtualenv
        - thunderbird
        - hexchat

    - name: Install essential packages
      apt:
        name: firefox
        state: latest
        update_cache: yes
        default_release: unstable

    - name: Mount WDC storage
      mount:
        path: /home/{{ item }}/storage/wdc
        src: UUID=f5dd74b8-5e4c-44e1-8c57-ea157fb57ec7
        fstype: ext4
        state: mounted
      with_items: "{{ sudoers }}"

    - name: Download skypeforlinux
      get_url:
        url: https://repo.skype.com/latest/skypeforlinux-64.deb
        dest: /tmp/skypeforlinux.deb

    - name: Install skypeforlinux
      apt: deb="/tmp/skypeforlinux.deb"

