---
- hosts: localhost
  connection: local
  become: false
  user: maciej
  vars:
    username: maciej
    wireless_iface: wlp6s0
    wired_iface: enp7s0
    git_name: "Maciej Pijanowski"
    git_email: "maciej.pijanowski@3mdeb.com"
  tasks:
    - include_role:
        name: "{{ role_name }}"
      with_items:
        - upgrade
        - packages_base
        - ssh
        - docker
        - git
        - packages_embedded
        - packages_extra
        - network_extra_maciej
        - ohmyzsh
        - vim
        - guake
      loop_control:
        loop_var: role_name
    - include_role:
        name: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "https://github.com/macpijan/dotfiles.git"
        dotfiles_repo_local_destination: "/home/{{ username }}/dotfiles"
        dotfiles_home: "/home/{{ username }}"
        dotfiles_files:
          - .gitconfig
          - .tmux.conf
          - .vimrc
          - .zshrc
