---
- hosts: localhost
  connection: local
  become: true
  user: maciej 
  vars:
    username: maciej
  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
        - upgrade
        - packages_base
        - packages_embedded
        - packages_extra
        - ohmyzsh
    - include_role:
        name: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "https://github.com/macpijan/dotfiles.git"
        dotfiles_repo_local_destination: "/home/{{ username }}/dotfiles"
        dotfiles_home: "/home/{{ username }}"
        dotfiles_files:
          - .gitconfig
