---
- name: Install Zsh and git
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - zsh

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.old; fi
  become: no

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  become: no

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  become: no

- name: Set Zsh as defult shell
  command: chsh -s /bin/zsh
