---
- name: Install Zsh and git
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - zsh
  become: true

- name: Backing up existing ~/.zshrc
  shell: "if [ -f /home/{{ username }}/.zshrc ]; then mv /home/{{ username }}/.zshrc /home/{{ username }}/.zshrc.old; fi"

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc

- name: Set Zsh as defult shell
  command: "chsh -s /bin/zsh {{ username }}"
  become: true
