- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - jq
    - curl
    - gparted
    - awscli
    - build-essential 
    - openssh-server
    - python
    - python-pip
    - virtualenv
    - docker
