- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - jq
    - curl
    - gparted
    - awscli
    - build-essential 
    - openssh-server
    - python
    - python-pip
    - virtualenv
    - docker

## snap install
# There is no ansible module for snap yet
- name: Install Slack from snap
  command: snap install slack

- name: Install Skype from snap
  command: snap install skype --classic
