---
- hosts: localhost
  connection: local
  user: "{{ username }}"
  become: false
  tasks:
    - include_role:
        name: "{{ role_name }}"
      with_items:
        - upgrade
        - packages_base
        - ssh
        - docker
        - git
      loop_control:
        loop_var: role_name
