- name: Install extra packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - virtualbox
    - nmap
    - vim
    - bvi
    - tmux
    - vim-gnome
    - guake
    - zsh

- name: Install oh-my-zsh
  shell: "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
