---
- name: Install openssh client and server
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - openssh-client
    - openssh-server
  become: true

- name: Start and enable ssh service
  service:
    name: ssh
    state: started
    enabled: yes

- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: true
  notify: restart ssh

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: true
  notify: restart ssh

- name: Create .ssh directory
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Create a 2048-bit SSH key for user
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "/home/{{ username }}/.ssh/id_rsa"
