---
- hosts: faroth
  user: debian
  become: yes
  become_user: root
  become_method: su
  roles:
    - role: debops.apt_preferences

  tasks:
    - name: Add Docker CE key to apt
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Remove cdrom repo
      apt_repository:
        repo: deb cdrom:[Debian GNU/Linux 9.4.0 _Stretch_ - Official amd64 xfce-CD Binary-1 20180310-11:21]/ stretch main
        state: absent

    - name: Add trffic manager stable deb repo
      apt_repository:
        repo: deb http://debian-archive.trafficmanager.net/debian/ stable main contrib non-free
        state: present

    - name: Add trffic manager stable deb-src repo
      apt_repository:
        repo: deb-src http://debian-archive.trafficmanager.net/debian/ stable main contrib non-free
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - python-pip

    - name: Install docker-py
      pip:
        name: docker-py

    - name: add default user to docker group
      user:
        name: debian
        groups: docker
        append: yes

    - name: Get netboot repository
      git:
        repo: https://github.com/3mdeb/netboot.git
        version: 0541b17ab70837b381f87a616309d229e31bb457 
        dest: /var/netboot
        force: yes

    - name: Set NFS server IP in netboot/menu.ipxe
      replace:
        path: /var/netboot/menu.ipxe
        regexp: 'replace_with_ip'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: Get kernels
      get_url:
        url: https://cloud.3mdeb.com/index.php/s/aGbBf0EkPYhGyY4/download
        dest: /tmp/kernels.tar.gz
        checksum: sha256:47369b2b49ac54b2ede68f19c56f433761110d455fd93f88d792f5fd6cd21c1b

    - name: Get Debian rootfs
      get_url:
        url: https://cloud.3mdeb.com/index.php/s/nV7za1cPtVGeERH/download
        dest: /tmp/debian-stable.tar.gz
        checksum: sha256:818a56a22882f4be8a0f5ce31096d87d6a30ac5749be645fdef98c7d167be6ff

    - name: Get Xen rootfs
      get_url:
        url: https://cloud.3mdeb.com/index.php/s/4WoGibldfRYqR4Z/download
        dest: /tmp/xen.tar.gz
        checksum: sha256:dbef67e29c4ec0a458c4b0e9645784d2d651f2210f5c6ab1e8b871c3c2562811

    - name: Get Voyage
      get_url:
        url: https://cloud.3mdeb.com/index.php/s/rUZPwRHOjxpSxN4/download
        dest: /tmp/voyage.tar.gz
        checksum: sha256:86934186fde2cbc749b2e33d027977f1b3a0cf02f69c2ffc9446e620b3d6e5c6
    
    - name: Get Core-6.4
      get_url:
        url: https://cloud.3mdeb.com/index.php/s/AQuUdsYkBzO9UJz/download
        dest: /tmp/core.tar.gz
        checksum: sha256:7fb624fe34b02b4df54c1e8c3b823b794441ef2b152480de7bb2c2b39f381be9

    - name: Create /var/voyage
      file:
        path: /var/voyage
        state: directory

    - name: Unarchive kernels
      unarchive:
        src: /tmp/kernels.tar.gz
        dest: /var/netboot
        remote_src: yes
        keep_newer: yes

    - name: Unarchive Debian rootfs
      unarchive:
        src: /tmp/debian-stable.tar.gz
        dest: /var/debian-stable
        remote_src: yes
        keep_newer: yes

    - name: Unarchive Xen rootfs
      unarchive:
        src: /tmp/xen.tar.gz
        dest: /var/xen
        remote_src: yes
        keep_newer: yes

    - name: Unarchive Voyage
      unarchive:
        src: /tmp/voyage.tar.gz
        dest: /var/voyage
        remote_src: yes
        keep_newer: yes

    - name: Unarchive Core
      unarchive:
        src: /tmp/core.tar.gz
        dest: /var/netboot/core-6.4
        remote_src: yes
        keep_newer: yes

    - name: Mount nfsd
      mount:
        path: /proc/fs/nfsd
        src: nfsd
        fstype: nfsd
        state: present

    - name: Start 3mdeb/pxe-server Docker container
      docker_container:
        name: pxe-server
        state: started
        image: 3mdeb/pxe-server:latest
        pull: yes
        command: bash /usr/local/bin/run.sh
        restart: yes
        restart_policy: always
        privileged: yes
        published_ports:
          - "111:111/tcp"
          - "2049:2049/tcp"
          - "8000:8000/tcp"
          - "627:627/tcp"
          - "627:627/udp"
          - "875:875/tcp"
          - "875:875/udp"
          - "892:892/tcp"
          - "892:892/udp"
          - "111:111/udp"
          - "2049:2049/udp"
          - "10053:10053/udp"
          - "10053:10053/tcp"
          - "32769:32769/tcp"
          - "32769:32769/udp"
          - "32765:32765/tcp"
          - "32765:32765/udp"
          - "32766:32766/tcp"
          - "32766:32766/udp"
          - "32767:32767/tcp"
          - "32767:32767/udp"
        volumes:
          - /var/netboot:/srv/http
          - /var/debian-stable:/srv/nfs/debian
          - /var/xen:/srv/nfs/xen
          - /var/voyage:/srv/nfs/voyage
