# I really prefer not to use NetworkManager
- name: Remove NetworkManager
  apt:
    name: network-manager
    state: absent
  become: true

- name: Install wpagui
  apt:
    name: wpagui
    state: present
  become: true

# and use plain systemd instead
- name: Wireless network systemd config
  template:
    src: 40-wireless-dhcp.network.j2
    dest: /etc/systemd/network/40-wireless-dhcp.network
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Wired network systemd config
  template:
    src: 50-wired-dhcp.network.j2
    dest: /etc/systemd/network/50-wired-dhcp.network
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start and enable systemd-networkd
  service:
    name: systemd-networkd
    state: started
    enabled: yes
  become: true

- name: Mount /storage and add fstab entry
  mount:
    src: "UUID={{ storage_uuid }}"
    fstype: ext4
    path: /storage
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add /storage mount entry to fstab
  lineinfile:
    path: /etc/fstab
    line: "UUID={{ storage_uuid }} /storage ext4 defaults 0 1"
    state: present
    owner: root
    group: root
    mode: 0644
  become: true

